[package]
name = "clipboard_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.10.3", package = "gtk4", features = ["v4_12"] }
libadwaita = { version = "0.8.1", features = ["v1_5"] }
